language: python
python:
   - "2.7"
virtualenv:
   system_site_packages: true
before_install:
   - "sudo apt-get install -qq pyton-numpy python-scipy"
install: 
   - "git submodule update --init --recursive"
script: nosetests
